# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 2.15.0
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: clippy
- repo: local
  hooks:
  - id: name test
    name: unit-test
    entry: cargo test
    language: system
    types: [rust]
    pass_filenames: false
