[package]
name = "rust"
version = "0.1.0"
authors = ["Ryan Bartling <ryan.bartling@thinkdeca.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "0.7.2"
rstest = "0.9.0"
structopt = "0.3.21"
