name: Static Analysis

on: [pull_request, push]


jobs:
  clippy:
    runs-on: ubuntu-latest

    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy -- -D warnings
